### PR TITLE
Remove XML/Crest reference, give community guys github links

### PR DESCRIPTION
**Pull request by NathenSample**

### CODE REVIEW

**Comment by a-tal** [comment]
should we add slack links as well, as per https://github.com/esi/esi-issues/commit/1fa0003bacabf2c6fccdcea56710894f33e0f945

**Comment by CarbonAlabel** [comment]
@a-tal I would say not. They only work if you're using Slack in the browser, and they provide a fairly shitty experience, as you're basically loading up another copy of Slack.

**Comment by a-tal** [comment]
took the table from #926 but i do like the removing xml and crest line from this PR.

@CarbonAlabel lol, you were the one who added them initially! is there a better slack proto we can link, maybe as a direct message to the person?

**Comment by CarbonAlabel** [comment]
That is what the links do, open a DM.
I just tried them out, and they still seem to be working, so I'd say it's safe to leave them in.

**Comment by a-tal** [comment]
seems we could also use `slack://user?team={TEAM_ID}&id={USER_ID}` to pop open the client instead of browser

from https://api.slack.com/docs/deep-linking#open_a_direct_message

**Comment by CarbonAlabel** [comment]
Yes, just found out about that. I managed to open a conversation with you using `slack://user?team=T03CDJ6FV&id=U0A4LT7BJ`, and other than the Slack app being laggy, it worked fine.

Downside is, this wouldn't work for browser Slack. Don't see an easy way to support both, and GitHub doesn't seem to like the `slack://` links very much.

**Comment by a-tal** [comment]
hmm. yeah that's kinda garbage then. maybe someday slack will improve that to where you can send them to the https version and it'll redirect to client if available, or something. 

anywho, yeah i agree not a big deal now it's probably fine as is.

@NathenSample if you want to remove the table from this PR that should remove the merge conflict

**Pull request merged**
